use_frameworks!

target 'MaLiang_Example' do
  pod 'MaLiang', :path => '../'
  pod 'Comet'
  pod 'Chrysan'
  pod 'Zip'
  pod 'SnapKit'
  



  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  pod 'SwiftHTTP', '~> 0.9.2'
end
